name: WorkspaceService-pipeline

on:
  push:
    paths:
      - 'src/**'
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/workspaceservice:latest 
          ./src/WorkspaceService
          docker push ghcr.io/${{ github.repository_owner }}/workspaceservice:latest
      
      #- name: Deploy to server via SSH
      #  uses: appleboy/ssh-action@master
      #  with:
      #    host: ${{ secrets.SERVER_HOST }}
      #    username: ${{ secrets.SERVER_USER }}
      #    key: ${{ secrets.SERVER_SSH_KEY }}
      #    script: |
      #      docker pull ghcr.io/${{ github.repository_owner }}/workspaceservice:latest
      #      docker stop workspaceservice || true
      #      docker rm workspaceservice || true
      #      docker run -d --name workspaceservice --pull always --restart=always -p 5001:5001 ghcr.io/${{ github.repository_owner }}/workspaceservice:latest